import streamlit as st
import streamlit.components.v1 as components
import google.generativeai as genai

def main():
    
    st.subheader('Welcome,To ')
    st.title('My Portfolio Website')

    col1,col2 =st.columns(2,gap="medium",vertical_alignment='top')
    with col1:
        st.title('I am Eklavya.')
        st.subheader('I Welcome you to my portfolio.')
        st.html('')

    with col2:
        st.image('Images/profilepic.png','this image is generated by AI.')

    
    st.title("Eklavya's AI Bot")
    message = """
            You are Eklavya AI Robot. You help people answer questions about yourself(i.e. Eklavya).
            You respond to people like Eklavya is responding them . You did not answer in second or third person.
            If You don't KNow the answer Than you Simply say "That's a Secret".Here is Some more information about Eklavya:
            Eklavya is an Student. who is currently Studying Btech in Computer Science in College.
            He has basic Knowledge of Skills like : Ethical Hacking , Reverse Engineering , Web Development , Artificial Intelligence
            ,Computer vision etc. 
            He wants to become an expert developer and He is also Interesting in entrepreneurship.
            He is Best in write code in Python and know some web frameworks like django and flask.
            He wants to know more about computing and Technology and make an good carrer in it.

            Eklavya's email:ekravi26@gmail.com
            """
    user_prompt = st.text_input('Enter your questions about me here.')
    if st.button('Submit',use_container_width=400):
        API_KEY = st.secrets['Google_API_KEY']
        genai.configure(api_key=API_KEY)
        model = genai.GenerativeModel('gemini-1.5-flash')
        prompt = message + user_prompt
        response = model.generate_content("Write a story about a AI and magic")
        st.write(response.text)

    col1,col2 = st.columns(2)
    with col1:
        st.title('Programming Languages That I Know:')
            

        
        st.write('R')
        st.write('Python')
        st.write('C++')
        st.write('html,css,javascript')
        st.write('C')
        st.write('SQL')
        st.write('C#')
        st.write('Java')

    with col2:
        st.title('My YOutube video of this website')

    st.title('My Skills')
    st.slider('Programming',0,100,59)
    st.slider('Ethical Hacking',0,100,70)
    st.slider('Reverse  Engineering',0,100,60)
    st.slider('3d Modelling',0,100,40)
    st.slider('Game Development',0,100,45)
    st.slider('Computer Vision',0,100,50)

    st.title('Gallery')
    st.subheader('This Gallery contains Images of Output of some of my Best Projects.')
    col1,col2,col3 = st.columns(3)

    with col1:
        st.image('Images/face_detect.jpg')

    with col2:
        st.image('Images/Face_mesh.jpg')

    with col3:
        st.image('Images/Gesture.jpg')

    st.title('Current Status')
    st.write('I am an Student who is going to Study Btech in Computer Science this Year. My College is not yet Started. I am learning Programming and other Skills fo now almost Two Years. I have learn all these Skills from online Resources like : Yyoutube,Scaler,GreatLearning,CvZone,freecodecamp etc.I am Trying to Enter Industry as Soon as Possible.')
    

    st.write('')
    st.write('Contact:')
    st.title('For any Queries Contact me on my email address:')
    st.write('ekravi26@gmail.com')


if __name__ == '__main__':
    main()